Module2 task1
htmlacademy-php/1816629-yeticave-12 pull request #3
Opened 2021-05-20 09:08 UTC by dantorde

2021-05-21 13:21 UTC, ademaro requested changes
В целом всё ок, но жду поправок, что бы двинуть дальше)

2021-05-21 13:21 UTC, ademaro commented on index.php
> +        'category' => 'Доски и лыжи',
можем ли мы связать значение с предыдущим массивом?

2021-05-21 13:21 UTC, ademaro commented on index.php
> +$categories = ['Доски и лыжи', 'Крепления', 'Ботинки', 'Одежда', 'Инструменты', 'Разное'];
предлагаю сделать ассоциативный массив, тк нам ещё нужна информация для модификаторов для каждого пункта меню, ключами массива как раз и могут быть модификаторы наши

2021-05-21 13:21 UTC, ademaro commented on index.php
> +        'price' => '10999',
какой тип данных? разве строка?

2021-05-21 13:21 UTC, ademaro commented on index.php
> +            <?php foreach ($categories as $val): ?>
почему val а не category?

2021-05-21 13:21 UTC, ademaro commented on index.php
>              <li class="promo__item promo__item--boards">
boards — как раз наш модификатор

2021-05-21 13:21 UTC, ademaro commented on index.php
> +            <?php foreach ($ads as $key => $val): ?>
ты тут используешь key? зачем инициализируешь? Ну и val переименуй

2021-05-24 06:24 UTC, ademaro approved these changes
Давай дальше, поправки жду в следующем задании

2021-05-24 06:24 UTC, ademaro commented on index.php
> +    "boards" => "Доски и лыжи",
двойные или одинарные кавычки всё-таки используем в проекте?)

2021-05-24 06:24 UTC, ademaro commented on index.php
>              <li class="promo__item promo__item--boards">
так почему модификатор не подставили?
`<li class="promo__item promo__item--<?= $key; ?>">`

2021-05-24 06:24 UTC, merged

2021-05-24 08:55 UTC, dantorde commented on index.php
> +    "boards" => "Доски и лыжи",
одинарные :)